### PR TITLE
Update Home.tsx with model

### PR DESCRIPTION
**Pull request by jenspapenhagen**
adding the model from the README.md into the rightplace

### CODE REVIEW

**Comment by johngthecreator** [comment]
Thanks! Missed that for some reason

**Comment by jenspapenhagen** [comment]
I really like your show project

**Comment by johngthecreator** [comment]
Thanks! I was working on it just as a test to try out local embedding models. I'm currently working with another developer on a package that lets you run a vector store in indexeddb if you're interested in that. It's called Vector Storage:

https://github.com/nitaiaharoni1/vector-storage

**Comment by johngthecreator** [comment]
Also if you have any experience setting up a CI/CD pipeline to deploy a docker image to docker hub on git push I'd be interested to see what you come up with

**Comment by jenspapenhagen** [comment]
> Thanks! I was working on it just as a test to try out local embedding models. I'm currently working with another developer on a package that lets you run a vector store in indexeddb if you're interested in that. It's called Vector Storage:
> 
> https://github.com/nitaiaharoni1/vector-storage

I will take a look at that. 


and the CI/CD for building and pushing the Dockerimage check this out:
https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

**Comment by jenspapenhagen** [comment]
Check this 
https://github.com/FireWork-Production-Private-Ltd/docker-repos/tree/main/.github/workflows

for pushing the dockerimage to docker-hub

**Comment by johngthecreator** [comment]
Awesome thank you! This is exactly what I was looking for

**Pull request merged**
